import { JWT } from 'google-auth-library'

const dotenv = require('dotenv')

dotenv.config({ path: `${__dirname}/../../../.env` })

console.log(
  'GOOGLE_SERVICE_ACCOUNT_EMAIL',
  process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL
)
console.log('GOOGLE_PRIVATE_KEY', process.env.GOOGLE_PRIVATE_KEY)

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
export const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n'),
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
})
